package codegen

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/bhs/mendelbuild/internal/db"
	"github.com/bhs/mendelbuild/internal/domain"
	"github.com/bhs/mendelbuild/internal/git"
	"github.com/google/uuid"
)

// GeneratorConfig holds configuration for the generator.
type GeneratorConfig struct {
	RepositoryURL string
	MainBranch    string
	AuthToken     string
	TestCommand   string
	APIKey        string
}

// Generator handles code generation for a single variation.
type Generator struct {
	db     *db.DB
	config GeneratorConfig
}

// NewGenerator creates a new Generator.
func NewGenerator(database *db.DB, config GeneratorConfig) *Generator {
	return &Generator{
		db:     database,
		config: config,
	}
}

// GenerateResult contains the result of code generation.
type GenerateResult struct {
	VariationID   uuid.UUID
	Success       bool
	CommitRef     string
	BranchName    string
	TokensUsed    int
	TestsPassed   bool
	Error         string
}

// Generate runs the full code generation workflow for a variation.
func (g *Generator) Generate(ctx context.Context, variation *domain.Variation, hopName string) (*GenerateResult, error) {
	result := &GenerateResult{
		VariationID: variation.ID,
	}

	// Create a logger that writes to the database
	logger := func(level domain.LogLevel, message string) {
		g.db.CreateVariationLog(ctx, variation.ID, level, message)
	}

	logger(domain.LogLevelMilestone, fmt.Sprintf("Starting code generation for variation '%s'", variation.Name))

	// 1. Clone repository to work directory
	workDir := git.WorkDirForVariation(variation.ID.String())
	gitClient := git.NewClient(workDir)
	defer gitClient.Cleanup()

	// Infrastructure failures use "error" status (retryable)
	// Code/test failures use "terminated" status (not retryable)

	logger(domain.LogLevelInfo, fmt.Sprintf("Cloning repository to %s", workDir))
	if err := gitClient.Clone(ctx, g.config.RepositoryURL, g.config.MainBranch, g.config.AuthToken); err != nil {
		result.Error = fmt.Sprintf("clone failed: %v", err)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusError, result.Error)
		return result, nil
	}
	logger(domain.LogLevelMilestone, "Repository cloned successfully")

	// 2. Create branch
	branchName := fmt.Sprintf("mendel/%s/%s", hopName, variation.Name)
	result.BranchName = branchName

	logger(domain.LogLevelInfo, fmt.Sprintf("Creating branch: %s", branchName))
	if err := gitClient.CreateBranch(ctx, branchName); err != nil {
		result.Error = fmt.Sprintf("create branch failed: %v", err)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusError, result.Error)
		return result, nil
	}

	// 3. Run Claude CLI
	cli := NewCLI(workDir, g.config.APIKey).WithLogger(logger)
	prompt := BuildImplementationPrompt(hopName, variation.Name, variation.Approach, g.config.TestCommand)

	cliResult, err := cli.Run(ctx, prompt)
	if err != nil {
		// CLI couldn't start - infrastructure error
		result.Error = fmt.Sprintf("cli run error: %v", err)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusError, result.Error)
		return result, nil
	}

	result.TokensUsed = cliResult.InputTokens + cliResult.OutputTokens

	if !cliResult.Success {
		// CLI ran but code generation failed - code issue, not retryable
		result.Error = fmt.Sprintf("cli failed: %s", cliResult.Error)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusTerminated, result.Error)
		return result, nil
	}

	// 4. Check for migration instructions
	if err := g.saveMigrationInstructions(ctx, workDir, variation.ID, logger); err != nil {
		// Log but don't fail - migrations are optional
		logger(domain.LogLevelInfo, fmt.Sprintf("No migration instructions: %v", err))
	}

	// 6. Run tests
	if g.config.TestCommand != "" {
		logger(domain.LogLevelInfo, fmt.Sprintf("Running tests: %s", g.config.TestCommand))
		testsPassed, testErr := g.runTests(ctx, workDir)
		result.TestsPassed = testsPassed

		if !testsPassed {
			// Tests failed - code issue, not retryable
			reason := "tests failed"
			if testErr != "" {
				reason = fmt.Sprintf("tests failed: %s", testErr)
			}
			result.Error = reason
			logger(domain.LogLevelError, reason)
			g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusTerminated, reason)
			return result, nil
		}
		logger(domain.LogLevelMilestone, "Tests passed")
	} else {
		result.TestsPassed = true // No tests configured
		logger(domain.LogLevelInfo, "No test command configured, skipping tests")
	}

	// 8. Commit changes
	logger(domain.LogLevelInfo, "Committing changes")
	commitMsg := fmt.Sprintf("[MendelBuild] %s: %s\n\nGenerated by MendelBuild for hop '%s'",
		variation.Name, truncate(variation.Approach, 50), hopName)

	if err := gitClient.CommitAll(ctx, commitMsg); err != nil {
		result.Error = fmt.Sprintf("commit failed: %v", err)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusError, result.Error)
		return result, nil
	}

	// 9. Get commit SHA
	commitRef, err := gitClient.GetCurrentCommit(ctx)
	if err != nil {
		result.Error = fmt.Sprintf("get commit ref failed: %v", err)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusError, result.Error)
		return result, nil
	}
	result.CommitRef = commitRef
	logger(domain.LogLevelMilestone, fmt.Sprintf("Committed: %s", commitRef[:8]))

	// 10. Push to remote
	logger(domain.LogLevelInfo, "Pushing to remote")
	if err := gitClient.Push(ctx, g.config.AuthToken); err != nil {
		result.Error = fmt.Sprintf("push failed: %v", err)
		logger(domain.LogLevelError, result.Error)
		g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusError, result.Error)
		return result, nil
	}
	logger(domain.LogLevelMilestone, fmt.Sprintf("Pushed branch: %s", branchName))

	// 11. Update variation with commit info
	variation.CommitRef = &commitRef
	variation.Status = domain.VariationStatusPending
	variation.UpdatedAt = time.Now()
	if err := g.db.UpdateVariation(ctx, variation); err != nil {
		result.Error = fmt.Sprintf("update variation failed: %v", err)
		logger(domain.LogLevelError, result.Error)
		return result, nil
	}

	// 12. Record state transition
	g.transitionState(ctx, variation.ID, domain.VariationStatusCreating, domain.VariationStatusPending, "code generation successful")

	logger(domain.LogLevelMilestone, "Code generation completed successfully!")
	result.Success = true
	return result, nil
}

// runTests executes the test command and returns whether tests passed.
func (g *Generator) runTests(ctx context.Context, workDir string) (bool, string) {
	// Parse test command (simple split for now)
	cmd := exec.CommandContext(ctx, "sh", "-c", g.config.TestCommand)
	cmd.Dir = workDir

	output, err := cmd.CombinedOutput()
	if err != nil {
		return false, string(output)
	}
	return true, ""
}

// MigrationInstructions is the structure written to .mendel/migration.json
type MigrationInstructions struct {
	UpInstructions   string `json:"up_instructions"`
	DownInstructions string `json:"down_instructions"`
	Notes            string `json:"notes"` // Where to find migration files in user's repo
}

// saveMigrationInstructions reads .mendel/migration.json if it exists and saves to DB.
func (g *Generator) saveMigrationInstructions(ctx context.Context, workDir string, variationID uuid.UUID, logger func(domain.LogLevel, string)) error {
	migrationPath := filepath.Join(workDir, ".mendel", "migration.json")

	data, err := os.ReadFile(migrationPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("no migration file (this is fine)")
		}
		return fmt.Errorf("read migration file: %w", err)
	}

	var instructions MigrationInstructions
	if err := json.Unmarshal(data, &instructions); err != nil {
		return fmt.Errorf("parse migration file: %w", err)
	}

	if instructions.UpInstructions == "" || instructions.DownInstructions == "" {
		return fmt.Errorf("migration file missing up_instructions or down_instructions")
	}

	// Save migration instructions to variation_migrations table
	migration := &domain.VariationMigration{
		ID:               uuid.New(),
		VariationID:      variationID,
		UpInstructions:   instructions.UpInstructions,
		DownInstructions: instructions.DownInstructions,
		CreatedAt:        time.Now(),
	}

	if err := g.db.CreateVariationMigration(ctx, migration); err != nil {
		return fmt.Errorf("save migration: %w", err)
	}

	// Save notes to variation record for easy reference
	if instructions.Notes != "" {
		v, err := g.db.GetVariation(ctx, variationID)
		if err == nil {
			v.MigrationNotes = &instructions.Notes
			g.db.UpdateVariation(ctx, v)
		}
	}

	logger(domain.LogLevelMilestone, "Saved migration instructions")
	if instructions.Notes != "" {
		logger(domain.LogLevelInfo, fmt.Sprintf("Migration files: %s", instructions.Notes))
	}
	return nil
}

// transitionState records a state transition in the database.
func (g *Generator) transitionState(ctx context.Context, variationID uuid.UUID, from, to domain.VariationStatus, reason string) {
	g.db.CreateVariationStateTransition(ctx, variationID, string(from), string(to), reason)

	// Also update the variation status
	v, err := g.db.GetVariation(ctx, variationID)
	if err == nil {
		v.Status = to
		v.UpdatedAt = time.Now()
		g.db.UpdateVariation(ctx, v)
	}
}

// truncate truncates a string to the given length.
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// ParseRepoConfig parses repository config JSON into a RepoConfig struct.
func ParseRepoConfig(config json.RawMessage) (*domain.RepoConfig, error) {
	if config == nil {
		return &domain.RepoConfig{}, nil
	}
	var rc domain.RepoConfig
	if err := json.Unmarshal(config, &rc); err != nil {
		return nil, err
	}
	return &rc, nil
}
