package envoy

import (
	"bytes"
	"context"
	"fmt"
	"text/template"

	"github.com/bhs/mendelbuild/internal/db"
	"github.com/bhs/mendelbuild/internal/domain"
	"github.com/google/uuid"
)

// Generator creates Envoy configurations from traffic allocations.
type Generator struct {
	db *db.DB
}

// NewGenerator creates a new Envoy config generator.
func NewGenerator(database *db.DB) *Generator {
	return &Generator{db: database}
}

// EndpointConfig represents a variation's endpoint for Envoy routing.
type EndpointConfig struct {
	Name    string  // Variation name
	Address string  // Service URL (host:port)
	Weight  int     // Traffic weight (0-100)
}

// ClusterConfig represents a hop's traffic routing configuration.
type ClusterConfig struct {
	HopID     string
	HopName   string
	Endpoints []EndpointConfig
}

// Config holds data for Envoy config template.
type Config struct {
	ListenerPort int
	HashHeader   string
	HealthPath   string
	Clusters     []ClusterConfig
}

// Generate creates an Envoy configuration for a project.
func (g *Generator) Generate(ctx context.Context, projectID uuid.UUID, opts GenerateOptions) (string, error) {
	// Get all hops for the project's strategy
	strategies, err := g.db.GetStrategiesByProject(ctx, projectID)
	if err != nil {
		return "", fmt.Errorf("get strategies: %w", err)
	}
	if len(strategies) == 0 {
		return "", fmt.Errorf("no strategy found for project")
	}

	var clusters []ClusterConfig

	for _, strategy := range strategies {
		hops, err := g.db.GetHopsByStrategy(ctx, strategy.ID)
		if err != nil {
			return "", fmt.Errorf("get hops: %w", err)
		}

		for _, hop := range hops {
			// Get traffic allocation for this hop
			allocation, err := g.db.GetTrafficAllocationByHop(ctx, hop.ID)
			if err != nil {
				// No allocation yet, skip
				continue
			}

			// Get slices for this allocation
			slices, err := g.db.GetTrafficAllocationSlices(ctx, allocation.ID)
			if err != nil {
				return "", fmt.Errorf("get allocation slices: %w", err)
			}
			if len(slices) == 0 {
				continue
			}

			var endpoints []EndpointConfig
			for _, slice := range slices {
				// Get deployed instance for this variation
				instance, err := g.db.GetDeployedInstanceByVariation(ctx, slice.VariationID)
				if err != nil {
					// No deployed instance, skip this slice
					continue
				}
				if instance.Status != domain.DeployedInstanceStatusRunning {
					continue
				}

				// Get variation name
				variation, err := g.db.GetVariation(ctx, slice.VariationID)
				if err != nil {
					continue
				}

				endpoints = append(endpoints, EndpointConfig{
					Name:    variation.Name,
					Address: instance.URL,
					Weight:  int(slice.Fraction * 100),
				})
			}

			if len(endpoints) > 0 {
				clusters = append(clusters, ClusterConfig{
					HopID:     hop.ID.String(),
					HopName:   hop.Name,
					Endpoints: endpoints,
				})
			}
		}
	}

	// Apply defaults
	config := Config{
		ListenerPort: opts.ListenerPort,
		HashHeader:   opts.HashHeader,
		HealthPath:   opts.HealthPath,
		Clusters:     clusters,
	}
	if config.ListenerPort == 0 {
		config.ListenerPort = 8080
	}
	if config.HashHeader == "" {
		config.HashHeader = "X-User-ID"
	}
	if config.HealthPath == "" {
		config.HealthPath = "/health"
	}

	// Render template
	return renderConfig(config)
}

// GenerateOptions holds options for config generation.
type GenerateOptions struct {
	ListenerPort int
	HashHeader   string
	HealthPath   string
}

func renderConfig(config Config) (string, error) {
	tmpl, err := template.New("envoy").Parse(envoyConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, config); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

const envoyConfigTemplate = `# Envoy configuration generated by Mendel
# Apply with: envoy -c envoy.yaml

admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901

static_resources:
  listeners:
  - name: main_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{.ListenerPort}}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
{{- range .Clusters}}
              - match:
                  prefix: "/"
                  headers:
                  - name: X-Mendel-Hop
                    exact_match: "{{.HopID}}"
                route:
                  cluster: {{.HopName}}_cluster
                  hash_policy:
                  - header:
                      header_name: {{$.HashHeader}}
{{- end}}
              - match:
                  prefix: "/"
                route:
                  cluster: default_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
{{- range .Clusters}}
  - name: {{.HopName}}_cluster
    type: STRICT_DNS
    lb_policy: RING_HASH
    ring_hash_lb_config:
      minimum_ring_size: 1024
    load_assignment:
      cluster_name: {{.HopName}}_cluster
      endpoints:
      - lb_endpoints:
{{- range .Endpoints}}
        - endpoint:
            address:
              socket_address:
                address: {{.Address}}
                port_value: 80
          load_balancing_weight: {{.Weight}}
{{- end}}
    health_checks:
    - timeout: 5s
      interval: 10s
      unhealthy_threshold: 2
      healthy_threshold: 1
      http_health_check:
        path: "{{$.HealthPath}}"
{{- end}}

  - name: default_cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: default_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 8081
`

// SaveConfig stores a generated config in the database.
func (g *Generator) SaveConfig(ctx context.Context, projectID uuid.UUID, configYAML string) (*domain.TrafficAllocationEnvoyConfig, error) {
	config := &domain.TrafficAllocationEnvoyConfig{
		ProjectID:  projectID,
		ConfigYAML: configYAML,
	}
	if err := g.db.CreateEnvoyConfig(ctx, config); err != nil {
		return nil, err
	}
	return config, nil
}

// GenerateAndSave generates and stores a config.
func (g *Generator) GenerateAndSave(ctx context.Context, projectID uuid.UUID, opts GenerateOptions) (*domain.TrafficAllocationEnvoyConfig, error) {
	yaml, err := g.Generate(ctx, projectID, opts)
	if err != nil {
		return nil, err
	}
	return g.SaveConfig(ctx, projectID, yaml)
}
